/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUDS;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyecto2dosemestre.Conexion;

/**
 *
 * @author Alessandro
 */
public class RENTA extends javax.swing.JFrame {

   ButtonGroup btngr;
    public RENTA() {
        initComponents();
       
        cargarSerie();
        cargarcliente();
        cargartipopago();
        cargarusuario();
        btngr = new ButtonGroup();
        // cargartabla();
        cargaridvehiculo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtidrenta = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        box1 = new javax.swing.JComboBox<>();
        box2 = new javax.swing.JComboBox<>();
        box3 = new javax.swing.JComboBox<>();
        box4 = new javax.swing.JComboBox<>();
        fprestamo = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblrenta = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        box6 = new javax.swing.JComboBox<>();
        jbAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("RENTA");

        jLabel2.setText("CORRELATIVO:");

        jLabel3.setText("SERIE");

        jLabel4.setText("CLIENTE");

        jLabel5.setText("ID_USUARIO");

        jLabel6.setText("ID_TIPO_PAGO");

        jLabel7.setText("FECHA_PRESTAMO");

        jLabel9.setText("TOTAL");

        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("MODIFICAR");

        jButton3.setText("ELIMINAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("LIMPIAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtidrenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidrentaActionPerformed(evt);
            }
        });

        txttotal.setText("0.00");
        txttotal.setEnabled(false);

        fprestamo.setDateFormatString("dd/MM/yyyy");

        tblrenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_VEHICULO", "DESCRIPCION", "PRECIO_ALQUILER"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblrenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblrentaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblrenta);

        jLabel11.setText("ID_VEHICULO");

        jbAgregar.setText("Agregar a Renta");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(560, 560, 560)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(33, 33, 33)
                                .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(box3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(box4, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtidrenta, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(575, 575, 575)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1354, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(box6, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbAgregar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidrenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(box4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(box3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(fprestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(box6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidrentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidrentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidrentaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        try{
            java.util.Date d = fprestamo.getDate();
            java.sql.Date FECHA_PRESTAMO = new java.sql.Date(d.getTime());
            
            JOptionPane.showMessageDialog(null,FECHA_PRESTAMO.toString());
            
            String id_tipo_pago = box3.getSelectedItem().toString().split(" | ")[0];
             
            String id_usuario = box4.getSelectedItem().toString().split(" | ")[0];
              
            String serie = box1.getSelectedItem().toString().split(" | ")[0];
            
            String id_cliente = box2.getSelectedItem().toString().split(" | ")[0];
            
           
            
            double TOTAL = 0.00;//Double.parseDouble(txttotal.getText());    
            
         
            
            Connection con = Conexion.getthatConexion();
            con.setAutoCommit(false);
            PreparedStatement ps = con.prepareStatement("INSERT INTO RENTA (ID_RENTA, SERIE, ID_CLIENTE, ID_USUARIO, ID_TIPO_PAGO, FECHA_PRESTAMO, TOTAL ) VALUES(?, ?, ?, ?, ?, ?, ?)");
             
            ps.setInt(1, Integer.parseInt(txtidrenta.getText()));
            ps.setInt(2, Integer.parseInt(serie)); 
            ps.setInt(3, Integer.parseInt(id_cliente)); 
            ps.setInt(4, Integer.parseInt(id_usuario)); 
            ps.setInt(5, Integer.parseInt(id_tipo_pago)); 
            ps.setDate(6, FECHA_PRESTAMO);
            ps.setDouble(7, TOTAL);
          
             
            ps.executeUpdate();
            
            con.commit();
            
            JOptionPane.showMessageDialog(null, "Registro Guardado");

            cargartabla();
            cargaridvehiculo();
        } catch(SQLException e){
            // JOptionPane.showMessageDialog(null, box3.getSelectedItem().toString().split(" | ")[0] );
            JOptionPane.showMessageDialog(null, e.toString());
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         int id = Integer.parseInt(txtidrenta.getText());
          String serie = box1.getSelectedItem().toString().split(" | ")[0];
           try{
            
            Connection con = Conexion.getthatConexion();
            PreparedStatement ps = con.prepareStatement("DELETE FROM RENTA WHERE ID_RENTA=?");
            
            // ps.setInt(1, ID_Usuario);
           
            ps.setInt(1, id);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro eliminado");
            LimpiarVariables();
            cargartabla();
                
        } catch(SQLException e){
        JOptionPane.showMessageDialog(null, e.toString());
        }   
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tblrentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblrentaMouseClicked
         try{
        
            int fila = tblrenta.getSelectedRow();
            int id = Integer.parseInt(tblrenta.getValueAt(fila, 0) .toString());
            
             PreparedStatement ps;
             ResultSet rs;
            
             Connection con = Conexion.getthatConexion();
   ps = con.prepareStatement("SELECT SERIE, ID_CLIENTE, ID_USUARIO, ID_TIPO_PAGO, FECHA_PRESTAMO, TOTAL FROM RENTA WHERE ID_RENTA=?");
   
   ps.setInt(1, id);
   rs = ps.executeQuery();
   
   while(rs.next()){
   txtidrenta.setText(String.valueOf(id));
    txttotal.setText(rs.getString("TOTAL"));
     
     
      
   }
        } catch(SQLException e){
          JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_tblrentaMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       cargarSerie();
       cargarcliente();
       cargartipopago();
       cargarSerie();
       cargarusuario();
       LimpiarVariables();
       cargaridvehiculo();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        ResultSet rs;
        ResultSetMetaData rsmd = null;
        try{
            String id_vehiculo = box6.getSelectedItem().toString().split(" | ")[0];
            
            String serie = box1.getSelectedItem().toString().split(" | ")[0];
            
            Connection con = Conexion.getthatConexion();
            
            PreparedStatement psPrecio = con.prepareStatement("SELECT PRECIO_ALQUILER FROM VEHICULO WHERE ID_VEHICULO = ? ");
            psPrecio.setInt(1, Integer.parseInt(id_vehiculo));
            
            rs = psPrecio.executeQuery();
            rsmd = rs.getMetaData();
            int columnas = rsmd.getColumnCount();
            String precio_renta = "";
            while(rs.next()){
                    precio_renta = rs.getString(1);
                }
            
            con.setAutoCommit(false);
            PreparedStatement ps = con.prepareStatement("INSERT INTO DETALLE_RENTA (ID_RENTA, SERIE, ID_VEHICULO, PRECIO_ALQUILER) VALUES(?, ?, ?, ?)");
             
            ps.setInt(1, Integer.parseInt(txtidrenta.getText()));
            ps.setInt(2, Integer.parseInt(serie)); 
            ps.setInt(3, Integer.parseInt(id_vehiculo));
            ps.setDouble(4, Double.parseDouble(precio_renta));
            
            double total = Double.parseDouble(txttotal.getText()) + Double.parseDouble(precio_renta) ;
            
            txttotal.setText(String.valueOf(total));
            
            ps.execute();
            
            PreparedStatement ps2 = con.prepareStatement("UPDATE RENTA SET TOTAL = ? WHERE ID_RENTA = ? AND SERIE = ?");
            
            ps2.setDouble(1, total);
            ps2.setInt(2, Integer.parseInt(txtidrenta.getText()));
            ps2.setInt(3, Integer.parseInt(serie)); 
            
            ps2.execute();
            
            PreparedStatement ps3 = con.prepareStatement("UPDATE VEHICULO SET ID_VEHICULO_ESTADO = 2 WHERE ID_VEHICULO = ? ");
            
            ps3.setInt(1, Integer.parseInt(id_vehiculo));
            
            ps3.execute();
            
            con.commit();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
         
        cargaridvehiculo();
        cargartabla();
    }//GEN-LAST:event_jbAgregarActionPerformed

    
 private void cargarSerie(){
     DefaultComboBoxModel modelocaja = (DefaultComboBoxModel) box1.getModel();
    // modelocaja.setSelectedItem(0);

    PreparedStatement ps;
    ResultSet rs;
    ResultSetMetaData rsmd = null;
    int columnas;


    try{
     Connection con = Conexion.getthatConexion();
      ps = con.prepareStatement("SELECT ID_SERIE, DESCRIPCION\n" +
   "  FROM [dbo].[SERIE]");
      rs = ps.executeQuery();
      rsmd = rs.getMetaData();
      columnas = rsmd.getColumnCount();

      while(rs.next()){
          String element = rs.getString(1) + " | " + rs.getString(2) ;
          modelocaja.addElement(element);

      }
    } catch(SQLException e){
    JOptionPane.showMessageDialog(null, e.toString());
    }
    }

private void cargarcliente(){

    DefaultComboBoxModel modelocaja = (DefaultComboBoxModel) box2.getModel();
    // modelocaja.setSelectedItem(0);

    PreparedStatement ps;
    ResultSet rs;
    ResultSetMetaData rsmd = null;
    int columnas;

   

    try{
     Connection con = Conexion.getthatConexion();
      ps = con.prepareStatement("SELECT ID_CLIENTE, CONCAT( [NIT], ' - ', [NOMBRE], ' ', [APELLIDO]) as DESCRIPCION\n" +
   "  FROM [dbo].[CLIENTE]");
      rs = ps.executeQuery();
      rsmd = rs.getMetaData();
      columnas = rsmd.getColumnCount();

      while(rs.next()){
          String element = rs.getString(1) + " | " + rs.getString(2) ;
          modelocaja.addElement(element);

      }
    } catch(SQLException e){
    JOptionPane.showMessageDialog(null, e.toString());
    }
 }
      
private void cargartipopago(){
 
 DefaultComboBoxModel modelocaja = (DefaultComboBoxModel) box3.getModel();
    // modelocaja.setSelectedItem(0);

    PreparedStatement ps;
    ResultSet rs;
    ResultSetMetaData rsmd = null;
    int columnas;

    

    try{
     Connection con = Conexion.getthatConexion();
      ps = con.prepareStatement("SELECT ID_TIPO_PAGO, DESCRIPCION\n" +
   "  FROM [dbo].[TIPO_PAGO]");
      rs = ps.executeQuery();
      rsmd = rs.getMetaData();
      columnas = rsmd.getColumnCount();

      while(rs.next()){
          String element = rs.getString(1) + " | " + rs.getString(2) ;
          modelocaja.addElement(element);
      }
    } catch(SQLException e){
    JOptionPane.showMessageDialog(null, e.toString());
    }
 }

private void cargarusuario(){

    DefaultComboBoxModel modelocaja = (DefaultComboBoxModel) box4.getModel();
    PreparedStatement ps;
    ResultSet rs;
    ResultSetMetaData rsmd = null;
    int columnas;


    try{
     Connection con = Conexion.getthatConexion();
      ps = con.prepareStatement("SELECT ID_USUARIO, CONCAT( [USUARIO], ' - ', [NOMBRE]) as DESCRIPCION\n" +
   "  FROM [dbo].[USUARIO] where [ESTADO] = 1");
      rs = ps.executeQuery();

      while(rs.next()){
          String element = rs.getString(1) + " | " + rs.getString(2) ;
          modelocaja.addElement(element);
      }
    } catch(SQLException e){
    JOptionPane.showMessageDialog(null, e.toString());
    }
 }




private void cargaridvehiculo(){
 
 DefaultComboBoxModel modelocaja = (DefaultComboBoxModel) box6.getModel();
    // modelocaja.setSelectedItem(0);

    PreparedStatement ps;
    ResultSet rs;
    ResultSetMetaData rsmd = null;
    int columnas;

    

    try{
     Connection con = Conexion.getthatConexion();
      ps = con.prepareStatement("SELECT ID_VEHICULO,  MODELO, PRECIO_ALQUILER" +
   "  FROM [dbo].[VEHICULO] where ID_VEHICULO_ESTADO = 1");
      rs = ps.executeQuery();
      rsmd = rs.getMetaData();
      columnas = rsmd.getColumnCount();

      while(rs.next()){
          String element = rs.getString(1) + " | " + rs.getString(2) + " | "  + rs.getString(3);
          modelocaja.addElement(element);
      }
    } catch(SQLException e){
    JOptionPane.showMessageDialog(null, e.toString());
    }
 }

private void cargartabla(){
 
 DefaultTableModel modelotabla = (DefaultTableModel) tblrenta.getModel();
 modelotabla.setRowCount(0);
 
 PreparedStatement ps;
 ResultSet rs;
 ResultSetMetaData rsmd = null;
 int columnas;
 
 
 try{
  Connection con = Conexion.getthatConexion();
   ps = con.prepareStatement("SELECT DR.ID_VEHICULO, VE.MODELO, DR.PRECIO_ALQUILER FROM DETALLE_RENTA DR, VEHICULO VE WHERE VE.ID_VEHICULO = DR.ID_VEHICULO  AND ID_RENTA = ? AND SERIE = ?");
   int id_renta = Integer.parseInt(txtidrenta.getText());
   int serie = Integer.parseInt(box1.getSelectedItem().toString().split(" | ")[0]);
   ps.setInt(1, id_renta);
   ps.setInt(2, serie);
   rs = ps.executeQuery();
   rsmd = rs.getMetaData();
   columnas = rsmd.getColumnCount();
   
   while(rs.next()){
      Object[] fila = new Object[columnas];
      for(int indice=0; indice<columnas; indice++){
      fila[indice] = rs.getObject(indice + 1);
      }
      modelotabla.addRow(fila);
   }
 } catch(SQLException e){
 JOptionPane.showMessageDialog(null, e.toString());
 }
 }
  
  private void LimpiarVariables(){
        txtidrenta.setText("");
        txttotal.setText("");
        btngr.clearSelection(); 
    }


    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RENTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RENTA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box1;
    private javax.swing.JComboBox<String> box2;
    private javax.swing.JComboBox<String> box3;
    private javax.swing.JComboBox<String> box4;
    private javax.swing.JComboBox<String> box6;
    private com.toedter.calendar.JDateChooser fprestamo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JTable tblrenta;
    private javax.swing.JTextField txtidrenta;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
