USE [master]
GO

/****** Object:  Database [proyecto]    Script Date: 10/21/2022 6:04:38 AM ******/
CREATE DATABASE [proyecto]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'proyecto', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\proyecto.mdf' , SIZE = 27648KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'proyecto_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\proyecto_log.ldf' , SIZE = 23552KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [proyecto].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [proyecto] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [proyecto] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [proyecto] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [proyecto] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [proyecto] SET ARITHABORT OFF 
GO

ALTER DATABASE [proyecto] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [proyecto] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [proyecto] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [proyecto] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [proyecto] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [proyecto] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [proyecto] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [proyecto] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [proyecto] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [proyecto] SET  DISABLE_BROKER 
GO

ALTER DATABASE [proyecto] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [proyecto] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [proyecto] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [proyecto] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [proyecto] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [proyecto] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [proyecto] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [proyecto] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [proyecto] SET  MULTI_USER 
GO

ALTER DATABASE [proyecto] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [proyecto] SET DB_CHAINING OFF 
GO

ALTER DATABASE [proyecto] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [proyecto] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [proyecto] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [proyecto] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [proyecto] SET QUERY_STORE = OFF
GO

ALTER DATABASE [proyecto] SET  READ_WRITE 
GO

